name: run jsonlds
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to soource JSONLDs from"
        required: false
        default: 'JSONLD_playground'
jobs:
  run-jsonlds:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: run-script
      run: python scripts/combine-jsonlds.py
