name: validate json files
on:
  workflow-dispatch:
jobs:
  validate-json-files:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: check jq version
      run: jq --version
    - name: run validation check
      run: |
        set -uo pipefall
        failures = ""
        count = 0
        for f in $(find src-data -type f -name '*.json'); do
          echo "validating $f"
          if jq . "$f" > /dev/null 2>&1; then
            echo "$f validated"
          else
            echo "WARNING: Invalid file detected for $f"
            failures = "$failures $f \n"
            count=$((count + 1))
          fi
        done

        if [ -n "$failures" ]; then
          echo "$count invalid files found..."
          echo -e "$failures"
          exit 1
        else
          echo " All files successfully validated"
        fi

          
