name: validate json files
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run check on"
        required: false
        default: 'store-src-data'
jobs:
  validate-json-files:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: run validation check
      run: |
        set -uo pipefail
        failures=""
        count=0
        while IFS= read -r -d '' f; do
          echo "validating $f"
          if ! error=$(jq . "$f" 2>&1 >/ dev/null); then
            echo "WARNING: Invalid file detected for $f"
            failures="$failures $f is not valid due to $error \n"
            count=$((count + 1))
          else
            echo "$f validated"
          fi
        done < <(find src-data -type f -name '*.json' -print0)

        if [ -n "$failures" ]; then
          echo "$count invalid files found..."
          echo -e "$failures"
          exit 1
        else
          echo "All files successfully validated"
        fi
          
